# Generated by Django 5.1.3 on 2025-08-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaPos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='tipo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
