# Generated by Django 5.1.3 on 2025-08-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaPos', '0002_movimientocaja_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('servicio', 'servicio')], default='libre', max_length=10),
        ),
    ]
